// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCReV9wPnKp3bdHRIPneFfdo0Kh9ckEvjI',
    appId: '1:615532445600:web:b4b95dd26ff95276a5eec5',
    messagingSenderId: '615532445600',
    projectId: 'musiumapp-e6f45',
    authDomain: 'musiumapp-e6f45.firebaseapp.com',
    storageBucket: 'musiumapp-e6f45.firebasestorage.app',
    measurementId: 'G-KRE7G0ZYF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8VAPQuN4ITNAc4Kx1FkC5_Hx76XT79yA',
    appId: '1:615532445600:android:f6ebe62abdf733f8a5eec5',
    messagingSenderId: '615532445600',
    projectId: 'musiumapp-e6f45',
    storageBucket: 'musiumapp-e6f45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFsMc_ie_ERM3w5uvQDrO8ym8yuFqGbXc',
    appId: '1:615532445600:ios:9f338fab07f2877ba5eec5',
    messagingSenderId: '615532445600',
    projectId: 'musiumapp-e6f45',
    storageBucket: 'musiumapp-e6f45.firebasestorage.app',
    iosBundleId: 'com.example.musium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFsMc_ie_ERM3w5uvQDrO8ym8yuFqGbXc',
    appId: '1:615532445600:ios:9f338fab07f2877ba5eec5',
    messagingSenderId: '615532445600',
    projectId: 'musiumapp-e6f45',
    storageBucket: 'musiumapp-e6f45.firebasestorage.app',
    iosBundleId: 'com.example.musium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCReV9wPnKp3bdHRIPneFfdo0Kh9ckEvjI',
    appId: '1:615532445600:web:9cf32de537dc7abca5eec5',
    messagingSenderId: '615532445600',
    projectId: 'musiumapp-e6f45',
    authDomain: 'musiumapp-e6f45.firebaseapp.com',
    storageBucket: 'musiumapp-e6f45.firebasestorage.app',
    measurementId: 'G-TN21XNYYG0',
  );
}
